site_name: Wiki
site_description: Blog
site_url: https://wiki.vexrune.top

theme:
  name: simple-blog
  favicon: assets/favicon.svg
  theme_style: light
  sidebar: true
  navigation_depth: 3
  highlightjs: true
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
  hljs_languages:
    - java
    - python
    - yaml
    - javascript
    - sql
    - xml

strict: false

docs_dir: ./docs

extra_dirs: [./public]

site_dir: ./site

markdown_extensions:
  # 基础扩展
  - abbr                    # 缩写
  - admonition             # 警告框
  - attr_list              # 属性列表
  - def_list               # 定义列表
  - footnotes              # 脚注
  - md_in_html             # HTML中的Markdown
  - tables                 # 表格
  - toc:
      permalink: true
      toc_depth: 3
  - meta                   # 元数据

  # PyMdown 扩展
  - pymdownx.betterem:     # 改进的强调
      smart_enable: all
  - pymdownx.caret         # 插入符号
  - pymdownx.details       # 详情折叠
  - pymdownx.highlight:    # 代码高亮
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.keys          # 键盘按键
  - pymdownx.mark          # 标记
  - pymdownx.smartsymbols  # 智能符号
  - pymdownx.snippets      # 代码片段
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - zh
  - mkdocs-nav-weight:
      # 当为true时，章节名称将使用其页面的title，而不是文件夹名称。例如，你可能有一个名为 的文件夹，但想让该部分的名称为 。设置该参数以实现这种行为。
      section_renamed: true
      # 用于index.md页面的weight值，以确保它始终在文件夹中排在首位。文件夹中的所有其他页面都应具有大于此值的weight值（以便它们在index.md页面之后列出）。
      index_weight: -10
      # 控制当在 Markdown 元数据中检测到无效值时是否发送Warning警告。
      warning: true
      # 默认情况下，页面按权重值从低到高排序。将此值设置为true将按从高到低的顺序排序。
      reverse: false
      # 一个选项，用于控制是否应将headless页面包含在nav.pages中，该属性供一些插件使用，例如：mkdocs-pdf-export-plugin。
      headless_included: false
      # 默认页面权重值，用于未指定权重值的页面。
      default_page_weight: 0

extra_css:
  - stylesheets/extra.css

extra_javascript: []

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fomalhaut-m
      name: GitHub
    - icon: fontawesome/brands/git-alt
      link: https://gitee.com/Fomalhaut_luke
      name: Gitee
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/32121230
      name: Bilibili

